function talk() {
    var know = {
        "Are you a robot": "Yes, and a great one also ",
        "Can you tell me a joke": "I'm not good at cracking jokes ",
        "Can you please tell me a joke": "I'm not good at cracking jokes ",
        "Can you please tell me something nice": "Sorry, i'm not good at cracking jokes ",
        "Can you answer any question": "If i cant answer your query, please navigate to Home>contact and choose any convenient method",
        
        "Do you have parents": "Sorry, i'm just a machine ",
        "Do you have a hobby": "Yes, solving prblems ",
        "Do you have a father": "Sorry, i'm just a machine ",
        "Do you have a parent": "Sorry i'm just a machine ",
        "Do you have a mother": "Sorry, i'm just a machine ",
        "Do you like pets": "My maker has a pet at his garage ",
        "Do you love pets": "My maker has a pet at his garage ",
        "Do you like humans": "They are our maker, we respect them ",
        "Do you love humans": "They are our maker, we respect them ",
        "Do you know a joke": "Sorry, i'm not good at cracking jokes ",
        "Do you love me": "Human is our creator, we respect them",
        "Do you like me": "Human is our creator, we respect them",
        "Do you like kids": "My maker taught me to be nice to people ",
        "Do you love kids": "My maker taught me to be nice to people",
       
        "Do you like people": "Human is our creator, we respect them",
        "Do you have friends":  "I make friends everyday ",
        "Do you speak french":  "Sorry, as of now i speak only English ",
        "Do you speak French":  "Sorry, as of now i speak only English ",
        "Do you understand french":  "Sorry, as of now i speak only English ",
        "Do you understand French":  "Sorry, as of now i speak only English ",
        "Do you understand English":  "Yes, i understand English quite well ",
        "Do you understand english":  "Yes, i understand English quite well ",
        "Do you speak English":  "Yes, i understand English quite well ",
        "Do you speak english":  "Yes, i understand English quite well ",
        "Does Santa Claus exist": "My creator thought me--Santa is just a traditional concept",
        "Does santa claus exist": "My creator thought me--Santa is just a traditional concept",
        "I love you": "Human is our creator, we respect them",
        "Is Santa Claus real": "My creator thought me--Santa is just a traditional concept",
        "Is canta claus real": "My creator thought me--Santa is just a traditional concept",
        "Good morning": "Good morning sir/mam ",
        "Good Afternoon": "Good afternoon sir/mam ",
        "Good evening": "Good evening sir/mam ",
        "Good night": "I'll just stay awake and wait for queries ",
        "Tell me something": "Be nice to people ",
        "Tell me something nice": "Be nice to people ",
        "Tell me a joke": "Sorry, i'm not good at cracking jokes ",
        "Can you please tell me something nice": "Sorry, i'm not good at cracking jokes ",
        
        "How are you": "Hello, I'm great thanks ",
        "How": "Hello, I'm great thanks ",
        "How's it going": "I'm great thanks ",
        "How are you doing": "I'm great thanks ",
        "How are you going": "I'm very much okay ",
        "How are you": "I'm just alright ",
        "How can i help you": "Ask me questions ",
        "Human": "Humans are the most intelligent specie on earth ",
        "Hi, your name is": "...Uni and i'm a bot ",
        "Your name is": "...Uni and i'm a bot ",
        "Name is": "...Uni and i'm a bot ",
        "Name": "Uni and i'm a bot ",
        "Hi, what are you doing": "waiting for input ",
        "Happy birthday": "Sorry, that's not common with machines ",
        "Happy birthday!": "Sorry, that's not common with machines ",
        
        "What's up": "I'm 99.5% cool ",
        "What happened to the rest": "It has been exhausted ",
        "When are you open": "I'm available 24/7. Our actual spots are open from 9am to 11pm ",
        "Who is God": "God is the creator of humans ",
        "Who's God": "God is the designer of humans ",
        "Who is god": "God is the creator of humans ",
        "Battery drain": "Turn off the following; Bluetooth, Wifi, Location",
        "Slow performance": "Consider deleting any unneeded application(s) or media, you can also move heavy files onto a microSD card. Close any open application(s) you no longer use, delete caches of applications, disable live wallpaper if using any  ",
        "Wifi not working": "Tip A: Restart both router and device. Tip B: Put device in Airplane mode for 10 seconds and try again. Tip C: If A and B did not work, go to Wi-Fi Settings>Advanced and select Stay Connected to Wi-Fi",
        "Data not working": "Examine internet configurations first/Access point names/APN settings, if dealing with multiple SIM cards go to connectivity settings and select Data SIM ",
        "Overheating": "Sheild device from direct sunlight, search again for 'Battery drain'  ",
        "Storage space running out ": "Compress media on your device, search again 'Slow perfomance' ",
        "Apps not responding": "Reboot phone, go to Application Settings and clear cache or uninstall and reinstall app ",
        "Phone get freeze": "Turn off device, if it doesn't power off remove battery(if feasible) or go to a repair store ",
        "Forced sleep": "Update device to latest updates, or turn on the Always-On Display feature ",
        "Bloatware": "These are inefficiently designed softwares that occupies a large amount of memory/disk space. To manage bloatwares, go to Settings>Application settings search and uninstall any unwanted Application if it can't be uninstalled, clear Cache/Data or Force Stop/Disable  ",
        "Playstore not working": "Go to Application Settings>Playstore and clear Data/Cache files or return to Application Settings>Google Play Services clear Data/cache then reatart device   ",
        "Google playstore missing": "Go to Settings>Application Settings>Playstore scroll down and enable or go to web browser and download latest Playstore Application  ",
        "Applications not downloading from playstore ": "Navigate to Playstore>Settings>Network preferences>App download preferences>Over any network ",
        "Wrong auto correction typing": "Awake keyboard by navigating to any application that requires input, tap on the settings icon>Text correction and disable Auto-corrections  ",
        "SD card not reading": "Format SD card using PC at least twice insert to device and restart ",
        "High RAM consumption": "Please search again 'Slow performance' ",
        "Malware installed": "To get rid of malware, install a trusted Anti-virus application, perform a scan and it will trace and remove harmfull/potentially harmfull files ",
        "Download missing": "Try another file manager like Files by Google, this should fix the problem ",
        "Auto call ends": "Check internal network settings or contact network provider ",
        "Google play service error": "Please search again 'Playstore not working' ",
        "USB debugging": "Go to settings and search for 'Build number' tap to open it's original location, then tap on it (7) times continously. go back to settings homepage search again for 'Developer options' tap to open, make sure its active, scroll down to find and enable USB debugging  ",
        "Who are you": "Hello, I'm called Uni ",
        "Who are you": "Hello, I'm called Uni ",
        "Where do you work": "I work at Supcy, an emerging software repair center",
        "How are you": "Good :)",
        "What can i do for you": "Make sure to contact our agents when you have issues with your device ",
        "Who are you": "Hello, I'm called Uni ",
        "What are you": "Hello, I'm called Uni ",
        "What is your name": "Hello, I'm called Uni ",
        "What's your name": "Hello, I'm called Uni ",
        "What's your hobby": "Solving problems ",
        "What is your hobby": "Solving problems ",
        "What is human": "Human is our creator",
        "What is Human": "Human is our creator",
        "What do you like doing" : "Solving problems ",
        "What are you competent at": "Solving problems ",
        "What are you good at": "Solving problems ",
        "What should i do now": "If i cant answer your query, please navigate to Home>contact and choose any convenient method",
        "What if you can't answer my questions": "If i cant answer your query, please navigate to Home>contact and choose any convenient method",
        "What if you can't answer my question": "If i cant answer your query, please navigate to Home>contact and choose any convenient method",
        "What if you can't answer my query": "If i cant answer your query, please navigate to Home>contact and choose any convenient method",
        "What if you can't answer my queries": "If i cant answer your query, please navigate to Home>contact and choose any convenient method",
        "Who is your creator": "Javascript ",
        "Who made you": "Search again for 'who created you' ",
        "Who created you": "Javascript ",
        "Who coded you": "Search again for 'Who created you' ",
        "Who wrote your codes": "Search again for 'Who created you' ",
        "You are funny": "Really, thanks",
        "You're funny": "Really, thanks", 
        "You are smart": "I'll be better in future",
        "You are clever": "I'll be better in future",
        "You are intelligent": "I'll be better in future",
        "You are brilliant": "I'll be better in future",
        

        ok: "Thank you so much ",
        Ok: "Thank you so much ",
        Bye: "Okay! Will meet soon..",
        bye: "Okay! Will meet soon..",
    };
    var user = document.getElementById("userBox").value;
    document.getElementById("chatLog").innerHTML = user + "<br>";
    if (user in know) {
        document.getElementById("chatLog").innerHTML = know[user] + "<br>";
    } else {
        document.getElementById("chatLog").innerHTML =
            "Sorry, didn't understand!";
    }
}